#!/usr/bin/env python3
"""Validate the odometry-only backend pose graph after a rosbag run."""

import argparse
import csv
import math
import statistics
from pathlib import Path
from typing import Dict, List, Sequence, Tuple


GRAPH_COLUMNS = {
    "solver",
    "id",
    "timestamp",
    "nodes",
    "odometry_factors",
    "optimization_ran",
    "solution_usable",
    "iterations",
    "initial_cost",
    "final_cost",
    "optimization_time_ms",
    "variables_relinearized",
    "variables_reeliminated",
    "raw_tx",
    "raw_ty",
    "raw_tz",
    "raw_qx",
    "raw_qy",
    "raw_qz",
    "raw_qw",
    "opt_tx",
    "opt_ty",
    "opt_tz",
    "opt_qx",
    "opt_qy",
    "opt_qz",
    "opt_qw",
    "position_delta_m",
    "angle_delta_deg",
}


def read_csv(path: Path) -> Tuple[Sequence[str], List[Dict[str, str]]]:
    if not path.is_file():
        raise RuntimeError(f"file does not exist: {path}")
    with path.open(newline="", encoding="utf-8") as stream:
        reader = csv.DictReader(stream)
        rows = list(reader)
        return reader.fieldnames or [], rows


def finite(row: Dict[str, str], columns: Sequence[str], row_id: int) -> List[float]:
    values = [float(row[column]) for column in columns]
    if not all(math.isfinite(value) for value in values):
        raise RuntimeError(f"row {row_id} contains a non-finite value")
    return values


def quaternion_angle_deg(left: Sequence[float], right: Sequence[float]) -> float:
    left_norm = math.sqrt(sum(value * value for value in left))
    right_norm = math.sqrt(sum(value * value for value in right))
    if abs(left_norm - 1.0) > 1.0e-5 or abs(right_norm - 1.0) > 1.0e-5:
        raise RuntimeError("encountered a non-unit quaternion")
    dot = abs(sum(a * b for a, b in zip(left, right)) / (left_norm * right_norm))
    return math.degrees(2.0 * math.acos(max(-1.0, min(1.0, dot))))


def percentile(values: Sequence[float], fraction: float) -> float:
    ordered = sorted(values)
    if not ordered:
        return 0.0
    index = min(len(ordered) - 1, int(math.ceil(fraction * len(ordered))) - 1)
    return ordered[index]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--graph",
        type=Path,
        default=Path("Log/backend/pose_graph.csv"),
        help="pose-graph CSV generated by the backend",
    )
    parser.add_argument(
        "--keyframes",
        type=Path,
        default=Path("Log/backend/keyframes.csv"),
        help="raw keyframe CSV from the same run",
    )
    parser.add_argument("--max-position-delta", type=float, default=5.0e-5)
    parser.add_argument("--max-angle-delta-deg", type=float, default=1.0e-2)
    parser.add_argument(
        "--additional-update-steps",
        type=int,
        default=1,
        help="must match backend.pose_graph.additional_update_steps",
    )
    args = parser.parse_args()
    if args.additional_update_steps < 0:
        raise RuntimeError("additional update steps must be non-negative")

    fields, rows = read_csv(args.graph)
    missing = sorted(GRAPH_COLUMNS.difference(fields))
    if missing:
        raise RuntimeError(f"pose-graph CSV is missing columns: {missing}")
    if len(rows) < 2:
        raise RuntimeError("pose graph must contain at least two keyframes")

    timestamps: List[float] = []
    optimization_times: List[float] = []
    position_deltas: List[float] = []
    angle_deltas: List[float] = []
    variables_relinearized: List[int] = []
    variables_reeliminated: List[int] = []
    optimization_runs = 0

    for index, row in enumerate(rows):
        row_id = int(row["id"])
        if row["solver"] != "gtsam_isam2":
            raise RuntimeError(
                f"row {index} was generated by {row['solver']!r}, not GTSAM iSAM2"
            )
        if row_id != index:
            raise RuntimeError(f"expected graph id {index}, got {row_id}")
        if int(row["nodes"]) != index + 1:
            raise RuntimeError(f"row {index} violates nodes == id + 1")
        if int(row["odometry_factors"]) != index:
            raise RuntimeError(f"row {index} violates factors == nodes - 1")

        timestamp = float(row["timestamp"])
        if timestamps and timestamp <= timestamps[-1]:
            raise RuntimeError(f"timestamp is not increasing at row {index}")
        timestamps.append(timestamp)

        ran = int(row["optimization_ran"])
        expected_run = int(index > 0)
        if ran != expected_run:
            raise RuntimeError(
                f"row {index}: optimization_ran={ran}, expected {expected_run}"
            )
        if int(row["solution_usable"]) != 1:
            raise RuntimeError(f"row {index} has an unusable solution")
        optimization_runs += ran
        relinearized = int(row["variables_relinearized"])
        reeliminated = int(row["variables_reeliminated"])
        if relinearized < 0 or reeliminated < 0:
            raise RuntimeError(f"row {index} has negative iSAM2 work counters")
        # A variable can be counted at most once inside each iSAM2 update.
        # The CSV row sums the primary update and all configured refinements.
        maximum_work = (index + 1) * (1 + args.additional_update_steps)
        if relinearized > maximum_work or reeliminated > maximum_work:
            raise RuntimeError(
                f"row {index} has impossible iSAM2 work counters: "
                f"relinearized={relinearized}, reeliminated={reeliminated}, "
                f"maximum={maximum_work}"
            )
        variables_relinearized.append(relinearized)
        variables_reeliminated.append(reeliminated)

        initial_cost, final_cost, elapsed = finite(
            row,
            ["initial_cost", "final_cost", "optimization_time_ms"],
            row_id,
        )
        if elapsed < 0.0:
            raise RuntimeError(f"row {index} has negative optimization time")
        if ran and final_cost > initial_cost + max(1.0e-12, abs(initial_cost) * 1.0e-9):
            raise RuntimeError(f"row {index} optimization increased the cost")
        if ran:
            optimization_times.append(elapsed)

        raw_t = finite(row, ["raw_tx", "raw_ty", "raw_tz"], row_id)
        opt_t = finite(row, ["opt_tx", "opt_ty", "opt_tz"], row_id)
        raw_q = finite(row, ["raw_qx", "raw_qy", "raw_qz", "raw_qw"], row_id)
        opt_q = finite(row, ["opt_qx", "opt_qy", "opt_qz", "opt_qw"], row_id)
        position_delta = math.sqrt(sum((a - b) ** 2 for a, b in zip(raw_t, opt_t)))
        angle_delta = quaternion_angle_deg(raw_q, opt_q)
        position_deltas.append(position_delta)
        angle_deltas.append(angle_delta)

        logged_position_delta = float(row["position_delta_m"])
        logged_angle_delta = float(row["angle_delta_deg"])
        if abs(position_delta - logged_position_delta) > 1.0e-9:
            raise RuntimeError(f"row {index} position delta log is inconsistent")
        if abs(angle_delta - logged_angle_delta) > 1.0e-5:
            raise RuntimeError(f"row {index} angle delta log is inconsistent")

    keyframe_fields, keyframe_rows = read_csv(args.keyframes)
    required_keyframe_fields = {"id", "timestamp", "tx", "ty", "tz", "qx", "qy", "qz", "qw"}
    if not required_keyframe_fields.issubset(keyframe_fields):
        raise RuntimeError("keyframe CSV does not contain the required pose columns")
    if len(keyframe_rows) != len(rows):
        raise RuntimeError(
            f"graph/keyframe row count differs: {len(rows)} != {len(keyframe_rows)}"
        )

    maximum_input_position_error = 0.0
    maximum_input_angle_error = 0.0
    maximum_timestamp_error = 0.0
    for graph_row, keyframe_row in zip(rows, keyframe_rows):
        graph_t = [float(graph_row[name]) for name in ("raw_tx", "raw_ty", "raw_tz")]
        keyframe_t = [float(keyframe_row[name]) for name in ("tx", "ty", "tz")]
        graph_q = [float(graph_row[name]) for name in ("raw_qx", "raw_qy", "raw_qz", "raw_qw")]
        keyframe_q = [float(keyframe_row[name]) for name in ("qx", "qy", "qz", "qw")]
        maximum_input_position_error = max(
            maximum_input_position_error,
            math.sqrt(sum((a - b) ** 2 for a, b in zip(graph_t, keyframe_t))),
        )
        maximum_input_angle_error = max(
            maximum_input_angle_error, quaternion_angle_deg(graph_q, keyframe_q)
        )
        maximum_timestamp_error = max(
            maximum_timestamp_error,
            abs(float(graph_row["timestamp"]) - float(keyframe_row["timestamp"])),
        )

    max_position_delta = max(position_deltas)
    max_angle_delta = max(angle_deltas)
    if max_position_delta > args.max_position_delta:
        raise RuntimeError(
            f"optimized/raw position delta {max_position_delta:.9g} m exceeds "
            f"{args.max_position_delta:.9g} m"
        )
    if max_angle_delta > args.max_angle_delta_deg:
        raise RuntimeError(
            f"optimized/raw angle delta {max_angle_delta:.9g} deg exceeds "
            f"{args.max_angle_delta_deg:.9g} deg"
        )
    if maximum_input_position_error > 1.0e-9 or maximum_input_angle_error > 1.0e-5:
        raise RuntimeError("pose-graph raw inputs differ from keyframe-manager output")
    if maximum_timestamp_error > 1.0e-9:
        raise RuntimeError("pose-graph timestamps differ from keyframe-manager output")

    print(
        f"pose graph: solver=gtsam_isam2, nodes={len(rows)}, "
        f"odometry_factors={len(rows) - 1}, "
        f"optimization_runs={optimization_runs}"
    )
    print(
        "optimized/raw equality: "
        f"max_position={max_position_delta:.9g}m, "
        f"max_angle={max_angle_delta:.9g}deg"
    )
    print(
        "graph/keyframe input equality: "
        f"max_dt={maximum_timestamp_error:.9g}s, "
        f"max_position={maximum_input_position_error:.9g}m, "
        f"max_angle={maximum_input_angle_error:.9g}deg"
    )
    if optimization_times:
        print(
            "optimization time: "
            f"median={statistics.median(optimization_times):.3f}ms, "
            f"p95={percentile(optimization_times, 0.95):.3f}ms, "
            f"max={max(optimization_times):.3f}ms"
        )
    print(
        "iSAM2 work: "
        f"relinearized_total={sum(variables_relinearized)}, "
        f"reeliminated_total={sum(variables_reeliminated)}, "
        f"max_reeliminated_per_keyframe={max(variables_reeliminated)}"
    )
    print("odometry pose-graph validation passed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, ValueError, KeyError) as error:
        print(f"validation failed: {error}")
        raise SystemExit(1)
